---
extends: airbnb-base
env:
  browser: true
  es6: true
globals:
  ENV: readonly
plugins:
  - import
rules:
  linebreak-style:
    - error
    - unix
  import/no-unresolved: 0
  no-multi-spaces:
    - 1
    - exceptions:
        VariableDeclarator: true
        ImportDeclaration: true
        AssignmentExpression: true
  comma-dangle:
    - error
    - only-multiline
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  padded-blocks: 0
  key-spacing: 0
  space-before-function-paren:
    - 2
    - never
  func-names:
    - 2
    - as-needed
  import/extensions: 0
