---
extends:
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
env:
  browser: true
  es6: true
globals:
  ENV: readonly
ignorePatterns:
  - esbuild.mjs
rules:
  no-undef: "warn"
  "@typescript-eslint/no-unused-vars":
    - "warn"
    - {
      "argsIgnorePattern": "^_",
      "varsIgnorePattern": "^_",
      "caughtErrorsIgnorePattern": "^_"
    }
